### ISSUE TITLE
Mixin into underscore.string if available?

### ISSUE THREAD

**Issue by shlajin** [jeremyruppel/underscore.inflection#30]
Hello and thanks for the amazing plugin.
`underscore_string` uses `s` global variable and offers optional mixin to `_` variable if you'd like, but that's not recommended. Since inflector works with string it makes sense to mixin methods to `s` global variable rather than in `_`.
What do you think?
Link to underscore.string -> https://github.com/epeli/underscore.string

**Comment by jeremyruppel** [comment]
Thanks for the suggestion, but my understanding is that underscore.string uses the `s` global by default because [several of its methods are named the same as underscore methods][1]. That's currently not a problem with this library, and we don't depend on underscore.string for any of our string manipulation, so I don't think we need to introduce a new dependency here.

[1]: https://github.com/epeli/underscore.string#underscorejslo-dash-integration
